apiVersion: apps/v1
kind: Deployment
metadata:
  name: geotracker-deploy
  namespace: geotracker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: geotracker
  template:
    metadata:
      labels:
        app: geotracker
    spec:
      containers:
        - name: geotracker
          image: registry.gitlab.com/magzhan_yedilbayev-group/geotracker:latest
          ports:
            - containerPort: 8080
          env:
            - name: IP
              value: "0.0.0.0"
            - name: PORT
              value: "8080"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: CONN_DB_POSTGRES
              value: "postgres://$(DB_USER):$(DB_PASSWORD)@postgres-service:5432/$(DB_NAME)?sslmode=disable"
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: geotracker-service
  namespace: geotracker
spec:
  type: NodePort
  selector:
    app: geotracker
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30085
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: geotracker
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  namespace: geotracker
spec:
  selector:
    matchLabels:
      app: postgres-geotracker
  template:
    metadata:
      labels:
        app: postgres-geotracker
    spec:
      containers:
        - name: postgres-geotracker
          image: postgres:15
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: geotracker
spec:
  type: ClusterIP
  selector:
    app: postgres-geotracker
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: geotracker
type: Opaque
stringData:
  POSTGRES_USER: "geotracker"
  POSTGRES_PASSWORD: "magzhan2006"
  POSTGRES_DB: "geotrackerDB"